//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIMPSTeam2Lead {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RU {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RU() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GIMPSTeam2Lead.RU", typeof(RU).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  * Larin Alexsandr.
        /// </summary>
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;p&quot;: { &quot;place&quot;: p.place, &quot;name&quot;: &quot;p.name&quot;, &quot;ghzdays&quot;: p.ghzdays },
        ///	&quot;c&quot;: { &quot;place&quot;: c.place, &quot;name&quot;: &quot;c.name&quot;, &quot;ghzdays&quot;: c.ghzdays },
        ///	&quot;n&quot;: { &quot;place&quot;: n.place, &quot;name&quot;: &quot;n.name&quot;, &quot;ghzdays&quot;: n.ghzdays }
        ///}.
        /// </summary>
        internal static string JSON {
            get {
                return ResourceManager.GetString("JSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  *.
        /// </summary>
        internal static string Mult {
            get {
                return ResourceManager.GetString("Mult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    Press any key to exit....
        /// </summary>
        internal static string PressAKey2Exit {
            get {
                return ResourceManager.GetString("PressAKey2Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    --------------------------------------------------------------------------------------------------------------.
        /// </summary>
        internal static string TBottom {
            get {
                return ResourceManager.GetString("TBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComputerraRU.
        /// </summary>
        internal static string TeamName {
            get {
                return ResourceManager.GetString("TeamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    | Type   | We * GHz-Days   |  To Leader | Lead Team                 |      To Us | Follower Team             |.
        /// </summary>
        internal static string TH {
            get {
                return ResourceManager.GetString("TH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIMPS Team 2 Lead.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  * http://computerraru.ru/software/gimpsteam2lead.
        /// </summary>
        internal static string URL {
            get {
                return ResourceManager.GetString("URL", resourceCulture);
            }
        }
    }
}
